/// <reference lib="webworker" />

import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Immediately activate and take control of the page
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('push', (event: any) => {
  let text = 'AUCUNE DONNÉE (event.data est null)';
  try {
    if (event.data) {
      text = event.data.text();
    }
  } catch (e: any) {
    text = 'ERREUR lecture data: ' + e.message;
  }

  event.waitUntil(
    self.registration.showNotification('PUSH DEBUG', { body: text })
  );
});
