// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  const customFetch = async (input: RequestInfo | URL, init?: RequestInit) => {
    try {
      const response = await fetch(input, init);
      const contentType = response.headers.get('content-type') || '';
      // Intercept any HTML response or 503/502 status which indicates Supabase is paused or down
      if (contentType.includes('text/html') || response.status === 503 || response.status === 502) {
        console.warn(`[Supabase Fetch Handler] Paused/inaccessible Supabase instance detected.`);
        const errorJson = {
          code: "SUPABASE_PAUSED",
          message: "Le serveur de base de données est actuellement en pause ou inaccessible. Veuillez réactiver le projet dans votre console Supabase ou vérifier votre connexion.",
          error: "Supabase project is paused or offline"
        };
        const blob = new Blob([JSON.stringify(errorJson)], { type: 'application/json' });
        return new Response(blob, {
          status: 400,
          statusText: 'Bad Request',
          headers: new Headers({
            'content-type': 'application/json'
          })
        });
      }
      return response;
    } catch (err: any) {
      console.warn(`[Supabase Fetch Handler] Network connection failure detected:`, err?.message || String(err));
      const errorJson = {
        code: "NETWORK_ERROR",
        message: "Problème de connexion réseau ou serveur injoignable.",
        error: err?.message || "Failed to fetch"
      };
      const blob = new Blob([JSON.stringify(errorJson)], { type: 'application/json' });
      return new Response(blob, {
        status: 400,
        statusText: 'Bad Request',
        headers: new Headers({
          'content-type': 'application/json'
        })
      });
    }
  };

  return createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: customFetch
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

